
let list = [
    { url: '100.gif', alt: '[微笑]' },
    { url: '101.gif', alt: '[撇嘴]' },
    { url: '102.gif', alt: '[色]' },
    { url: '103.gif', alt: '[发呆]' },
    { url: '104.gif', alt: '[得意]' },
    { url: '105.gif', alt: '[流泪]' },
    { url: '106.gif', alt: '[害羞]' },
    { url: '107.gif', alt: '[闭嘴]' },
    { url: '108.gif', alt: '[睡]' },
    { url: '109.gif', alt: '[大哭]' },
    { url: '100.gif', alt: '[尴尬]' },
    { url: '111.gif', alt: '[发怒]' },
    { url: '112.gif', alt: '[调皮]' },
    { url: '113.gif', alt: '[呲牙]' },
    { url: '114.gif', alt: '[惊讶]' },
    { url: '115.gif', alt: '[难过]' },
    { url: '116.gif', alt: '[酷]' },
    { url: '117.gif', alt: '[冷汗]' },
    { url: '118.gif', alt: '[抓狂]' },
    { url: '119.gif', alt: '[吐]' },
    { url: '120.gif', alt: '[偷笑]' },
    { url: '121.gif', alt: '[愉快]' },
    { url: '122.gif', alt: '[白眼]' },
    { url: '123.gif', alt: '[傲慢]' },
    { url: '124.gif', alt: '[饥饿]' },
    { url: '125.gif', alt: '[困]' },
    { url: '126.gif', alt: '[惊恐]' },
    { url: '127.gif', alt: '[流汗]' },
    { url: '128.gif', alt: '[憨笑]' },
    { url: '129.gif', alt: '[悠闲]' },
    { url: '130.gif', alt: '[奋斗]' },
    { url: '131.gif', alt: '[咒骂]' },
    { url: '132.gif', alt: '[疑问]' },
    { url: '133.gif', alt: '[嘘]' },
    { url: '134.gif', alt: '[晕]' },
    { url: '135.gif', alt: '[疯了]' },
    { url: '136.gif', alt: '[衰]' },
    { url: '137.gif', alt: '[骷髅]' },
    { url: '138.gif', alt: '[敲打]' },
    { url: '139.gif', alt: '[再见]' },
    { url: '140.gif', alt: '[擦汗]' },
    { url: '141.gif', alt: '[抠鼻]' },
    { url: '142.gif', alt: '[鼓掌]' },
    { url: '143.gif', alt: '[糗大了]' },
    { url: '144.gif', alt: '[坏笔]' },
    { url: '145.gif', alt: '[左哼哼]' },
    { url: '146.gif', alt: '[右哼哼]' },
    { url: '147.gif', alt: '[哈欠]' },
    { url: '148.gif', alt: '[鄙视]' },
    { url: '149.gif', alt: '[委屈]' },
    { url: '150.gif', alt: '[快哭了]' },
    { url: '151.gif', alt: '[阴险]' },
    { url: '152.gif', alt: '[亲亲]' },
    { url: '153.gif', alt: '[吓]' },
    { url: '154.gif', alt: '[可怜]' },
    { url: '155.gif', alt: '[菜刀]' },
    { url: '156.gif', alt: '[西瓜]' },
    { url: '157.gif', alt: '[啤酒]' },
    { url: '158.gif', alt: '[篮球]' },
    { url: '159.gif', alt: '[乒乓]' },
    { url: '160.gif', alt: '[咖啡]' },
    { url: '161.gif', alt: '[饭]' },
    { url: '162.gif', alt: '[猪头]' },
    { url: '163.gif', alt: '[玫瑰]' },
    { url: '164.gif', alt: '[凋谢]' },
    { url: '165.gif', alt: '[嘴唇]' },
    { url: '166.gif', alt: '[爱心]' },
    { url: '167.gif', alt: '[心碎]' },
    { url: '168.gif', alt: '[蛋糕]' },
    { url: '169.gif', alt: '[闪电]' },
    { url: '170.gif', alt: '[炸弹]' },
    { url: '171.gif', alt: '[刀]' },
    { url: '172.gif', alt: '[足球]' },
    { url: '173.gif', alt: '[瓢虫]' },
    { url: '174.gif', alt: '[便便]' },
    { url: '175.gif', alt: '[月亮]' },
    { url: '176.gif', alt: '[太阳]' },
    { url: '177.gif', alt: '[礼物]' },
    { url: '178.gif', alt: '[拥抱]' },
    { url: '179.gif', alt: '[强]' },
    { url: '180.gif', alt: '[弱]' },
    { url: '181.gif', alt: '[握手]' },
    { url: '182.gif', alt: '[胜利]' },
    { url: '183.gif', alt: '[抱拳]' },
    { url: '184.gif', alt: '[勾引]' },
    { url: '185.gif', alt: '[拳头]' },
    { url: '186.gif', alt: '[差劲]' },
    { url: '187.gif', alt: '[爱你]' },
    { url: '188.gif', alt: '[NO]' },
    { url: '189.gif', alt: '[OK]' },
    { url: '190.gif', alt: '[爱情]' },
    { url: '191.gif', alt: '[飞吻]' },
    { url: '192.gif', alt: '[跳跳]' },
    { url: '193.gif', alt: '[发抖]' },
    { url: '194.gif', alt: '[怄火]' },
    { url: '195.gif', alt: '[转圈]' },
    { url: '196.gif', alt: '[磕头]' },
    { url: '197.gif', alt: '[回头]' },
    { url: '198.gif', alt: '[跳绳]' },
    { url: '199.gif', alt: '[投降]' }
]

for(let i = 0; i < list.length; i++) {
	list[i].url = require(`../assets/emoji/${list[i].url}`)
}

// for(let i = 0; i <= 19; i++) {
// 	list.push({
// 		url: require(`../assets/emoji/${200 + i}.png`)
// 	})
// }


export default list