const ICO_PREP = 'http://www.google.cn/s2/favicons?domain='

let urlList = [{
    "title": "回收站",
    "files": 1,
    "x": 280,
    "y": 455,
    "show": 0,
    "children": []
},
// {
//     "title": "账号记录",
//     "text": 1,
//     "x": 280,
//     "y": 455,
//     "show": 0,
//     "html": '密码：123456'
// },
{
    "url": "http://www.baidu.com",
    "title": "百度",
    "icon": "http://www.google.cn/s2/favicons?domain=http://www.baidu.com",
    "x": 0,
    "y": 91
},{
    "url": "https://account.wps.cn",
    "title": "金山文档",
    "icon": "http://www.google.cn/s2/favicons?domain=https://account.wps.cn",
    "x": 0,
    "y": 91
}, {
    "url": "http://map.baidu.com/",
    "title": "百度地图",
    "icon": "http://www.google.cn/s2/favicons?domain=http://map.baidu.com/",
    "x": 0,
    "y": 91
},{
    "url": "https://pan.baidu.com",
    "title": "百度网盘",
    "icon": "https://pan.baidu.com/static/images/favicon.ico"
},{
    "url": "https://union-click.jd.com/",
    "title": "京东",
    "icon": "http://www.google.cn/s2/favicons?domain=https://union-click.jd.com/",
    "x": 70,
    "y": 91
},{
    "url": "https://www.taobao.com/",
    "title": "淘宝网",
    "icon": "http://www.google.cn/s2/favicons?domain=https://www.taobao.com/",
    "x": 70,
    "y": 182
},{
    "url": "https://36kr.com/",
    "title": "36氪",
    "icon": "https://img.36krcdn.com/20191024/v2_1571894049839_img_jpg",
    "x": 70,
    "y": 182
},{
    "url": "http://www.iqiyi.com/",
    "title": "爱奇艺",
    "icon": "http://www.google.cn/s2/favicons?domain=http://www.iqiyi.com/",
    "x": 70,
    "y": 182
}, {
    "url": "https://translate.google.cn",
    "title": "谷歌翻译",
    "icon": "http://www.google.cn/s2/favicons?domain=https://translate.google.cn",
    "x": 0,
    "y": 91
},
{
    "url": "https://weibo.com/",
    "title": "微博",
    "icon": "http://www.google.cn/s2/favicons?domain=https://weibo.com/",
    "x": 0,
    "y": 91
}, {
    "title": "视频",
    "files": 1,
    "x": 280,
    "y": 455,
    "show": 0,
    "children": [
    {
        "url": "https://www.bilibili.com/",
        "title": "哔哩哔哩",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.bilibili.com/",
        "x": 140,
        "y": 273
    },{
        "url": "https://haokan.baidu.com/",
        "title": "好看视频",
        "icon": "http://www.google.cn/s2/favicons?domain=https://haokan.baidu.com/"
    }, {
        "url": "http://www.iqiyi.com/",
        "title": "爱奇艺高清",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.iqiyi.com/"
    }, {
        "url": "http://www.youku.com/",
        "title": "优酷网",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.youku.com/"
    }, {
        "url": "http://v.baidu.com/",
        "title": "百度视频",
        "icon": "http://www.google.cn/s2/favicons?domain=http://v.baidu.com/"
    }, {
        "url": "https://quanmin.baidu.com/",
        "title": "全民小视频",
        "icon": "http://www.google.cn/s2/favicons?domain=https://quanmin.baidu.com/"
    }, {
        "url": "http://v.qq.com/",
        "title": "腾讯视频",
        "icon": "http://www.google.cn/s2/favicons?domain=http://v.qq.com/"
    }, {
        "url": "http://www.mgtv.com/",
        "title": "芒果TV",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.mgtv.com/"
    }, {
        "url": "https://tv.sohu.com/",
        "title": "搜狐视频",
        "icon": "http://www.google.cn/s2/favicons?domain=https://tv.sohu.com/"
    }, {
        "url": "http://www.pptv.com/",
        "title": "PPTV",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.pptv.com/"
    }]
}, {
    "title": "新闻",
    "files": 1,
    "x": 280,
    "y": 455,
    "show": 0,
    "children": [{
        "url": "http://news.sina.com.cn/",
        "title": "新浪新闻",
        "icon": "http://www.google.cn/s2/favicons?domain=http://news.sina.com.cn/"
    }, {
        "url": "http://www.qq.com/",
        "title": "腾讯新闻",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.qq.com/"
    }, {
        "url": "https://www.guancha.cn/",
        "title": "观察者网",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.guancha.cn/"
    }, {
        "url": "http://news.sohu.com/",
        "title": "搜狐新闻",
        "icon": "http://www.google.cn/s2/favicons?domain=http://news.sohu.com/"
    }, {
        "url": "http://www.cankaoxiaoxi.com/",
        "title": "参考消息",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.cankaoxiaoxi.com/"
    }, {
        "url": "http://www.huanqiu.com/",
        "title": "环球网",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.huanqiu.com/"
    }, {
        "url": "https://junshi.china.com/",
        "title": "中华军事",
        "icon": "http://www.google.cn/s2/favicons?domain=https://junshi.china.com/"
    }, {
        "url": "http://news.ifeng.com/mil/",
        "title": "凤凰军事",
        "icon": "http://www.google.cn/s2/favicons?domain=http://news.ifeng.com/mil/"
    }, {
        "url": "http://www.miercn.com/",
        "title": "米尔军事",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.miercn.com/"
    }]
}, {
    "title": "综合",
    "files": 1,
    "x": 280,
    "y": 455,
    "show": 0,
    "children": [{
        "url": "http://www.sina.com.cn/",
        "title": "新浪",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.sina.com.cn/",
        "x": 0,
        "y": 91
    },  {
        "url": "http://www.sohu.com/",
        "title": "搜狐",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.sohu.com/",
        "x": 0,
        "y": 91
    }, {
        "url": "http://www.qq.com/",
        "title": "腾讯",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.qq.com/",
        "x": 0,
        "y": 91
    }, {
        "url": "http://www.163.com/",
        "title": "网易",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.163.com/",
        "x": 0,
        "y": 91
    },{
        "url": "https://www.douban.com/",
        "title": "豆瓣网",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.douban.com/",
        "x": 280,
        "y": 455
    },{
        "url": "https://www.gaodun.com",
        "title": "高顿教育",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.gaodun.com"
    }, {
        "url": "https://www.58pic.com/",
        "title": "千图网",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.58pic.com/"
    }, {
        "url": "https://wenku.baidu.com/",
        "title": "百度文库",
        "icon": "http://www.google.cn/s2/favicons?domain=https://wenku.baidu.com/"
    }, {
        "url": "https://www.275.com/",
        "title": "学霸说保险网",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.275.com/"
    }, {
        "url": "https://open.163.com",
        "title": "网易公开课",
        "icon": "http://www.google.cn/s2/favicons?domain=https://open.163.com"
    }, {
        "url": "https://www.csdn.net/",
        "title": "CSDN社区",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.csdn.net/"
    }, {
        "url": "http://www.weatherol.com",
        "title": "本地天气",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.weatherol.com"
    }, {
        "url": "http://www.pbccrc.org.cn/",
        "title": "征信中心",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.pbccrc.org.cn/"
    }, {
        "url": "http://www.cpta.com.cn/",
        "title": "人事考试网",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.cpta.com.cn/",
        "x": 280,
        "y": 455
    },{
        "url": "http://e.baidu.com/",
        "title": "百度营销",
        "icon": "http://www.google.cn/s2/favicons?domain=http://e.baidu.com/"
    },{
        "url": "https://www.chsi.com.cn/",
        "title": "学信网",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.chsi.com.cn/",
        "x": 210,
        "y": 364
    },{
        "url": "https://www.icourse163.org/",
        "title": "中国大学MOOC",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.icourse163.org/",
        "x": 210,
        "y": 364
    }, {
        "url": "http://www.12306.cn/",
        "title": "12306",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.12306.cn/",
        "x": 210,
        "y": 364
    }, {
        "url": "https://www.qcc.com/",
        "title": "企查查",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.qcc.com/",
        "x": 210,
        "y": 364
    },{
        "url": "http://www.cnki.net/",
        "title": "知网",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.cnki.net/",
        "x": 140,
        "y": 273
    }, {
        "url": "http://www.zhihu.com/",
        "title": "知乎",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.zhihu.com/",
        "x": 140,
        "y": 273
    }, {
        "url": "http://xueshu.baidu.com/",
        "title": "百度学术",
        "icon": "http://www.google.cn/s2/favicons?domain=http://xueshu.baidu.com/",
        "x": 210,
        "y": 364
    },]
}, {
    "title": "购物",
    "files": 1,
    "x": 280,
    "y": 455,
    "show": 0,
    "children": [{
        "url": "https://s.click.taobao.com/",
        "title": "爱淘宝",
        "icon": "http://www.google.cn/s2/favicons?domain=https://s.click.taobao.com/"
    }, {
        "url": "https://www.suning.com/",
        "title": "苏宁易购",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.suning.com/"
    }, {
        "url": "https://mos.m.taobao.com/",
        "title": "聚划算",
        "icon": "http://www.google.cn/s2/favicons?domain=https://mos.m.taobao.com/"
    }, {
        "url": "https://s.click.taobao.com",
        "title": "天猫特卖",
        "icon": "http://www.google.cn/s2/favicons?domain=https://s.click.taobao.com"
    }, {
        "url": "https://union-click.jd.com/",
        "title": "京东商城",
        "icon": "http://www.google.cn/s2/favicons?domain=https://union-click.jd.com/"
    }, {
        "url": "https://s.click.taobao.com/",
        "title": "天猫超市",
        "icon": "http://www.google.cn/s2/favicons?domain=https://s.click.taobao.com/"
    }, {
        "url": "https://p.yiqifa.org/5WB6Sl",
        "title": "唯品会",
        "icon": "http://www.google.cn/s2/favicons?domain=https://p.yiqifa.org/5WB6Sl",
        "x": 140,
        "y": 273
    }, {
        "url": "https://qiang.suning.com",
        "title": "苏宁秒杀",
        "icon": "http://www.google.cn/s2/favicons?domain=https://qiang.suning.com",
        "x": 140,
        "y": 273
    },{
        "url": "http://www.dangdang.com/",
        "title": "当当网",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.dangdang.com/"
    }, {
        "url": "https://www.taobao.com/",
        "title": "淘宝网",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.taobao.com/"
    }, {
        "url": "http://www.mogujie.com/",
        "title": "蘑菇街",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.mogujie.com/"
    }, {
        "url": "https://www.1688.com/",
        "title": "1688",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.1688.com/"
    }]
}, {
    "title": "游戏",
    "files": 1,
    "x": 350,
    "y": 455,
    "show": 0,
    "children": [{
        "url": "http://www.4399.com/",
        "title": "4399游戏",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.4399.com/"
    }, {
        "url": "http://game.baidu.com/",
        "title": "百度游戏",
        "icon": "http://www.google.cn/s2/favicons?domain=http://game.baidu.com/"
    }, {
        "url": "https://syzs.qq.com/",
        "title": "王者荣耀",
        "icon": "http://www.google.cn/s2/favicons?domain=https://syzs.qq.com/"
    }, {
        "url": "http://www.7k7k.com/",
        "title": "7k7k游戏",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.7k7k.com/"
    }, {
        "url": "http://www.17173.com/",
        "title": "17173",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.17173.com/"
    }, {
        "url": "http://www.gamersky.com/",
        "title": "游民星空",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.gamersky.com/"
    }, {
        "url": "http://game.baidu.com/",
        "title": "百度游戏",
        "icon": "http://www.google.cn/s2/favicons?domain=http://game.baidu.com/"
    }]
}, {
    "title": "体育",
    "files": 1,
    "x": 350,
    "y": 455,
    "show": 0,
    "children": [{
        "url": "http://sports.sina.com.cn/",
        "title": "新浪体育",
        "icon": "http://www.google.cn/s2/favicons?domain=http://sports.sina.com.cn/"
    }, {
        "url": "http://sports.sohu.com/",
        "title": "搜狐体育",
        "icon": "http://www.google.cn/s2/favicons?domain=http://sports.sohu.com/"
    }, {
        "url": "http://sports.cntv.cn/",
        "title": "CCTV5",
        "icon": "http://www.google.cn/s2/favicons?domain=http://sports.cntv.cn/"
    }, {
        "url": "https://www.hupu.com/",
        "title": "虎扑体育",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.hupu.com/"
    }, {
        "url": "http://www.zhibo8.cc/",
        "title": "直播吧",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.zhibo8.cc/"
    }, {
        "url": "http://sports.163.com/",
        "title": "网易体育",
        "icon": "http://www.google.cn/s2/favicons?domain=http://sports.163.com/"
    }, {
        "url": "http://sports.qq.com/",
        "title": "腾讯体育",
        "icon": "http://www.google.cn/s2/favicons?domain=http://sports.qq.com/"
    }, {
        "url": "http://sports.ifeng.com/",
        "title": "凤凰体育",
        "icon": "http://www.google.cn/s2/favicons?domain=http://sports.ifeng.com/"
    }, {
        "url": "http://sports.iqiyi.com/",
        "title": "爱奇艺体育",
        "icon": "http://www.google.cn/s2/favicons?domain=http://sports.iqiyi.com/"
    }]
}, {
    "title": "小说",
    "files": 1,
    "x": 350,
    "y": 546,
    "show": 0,
    "children": [{
        "url": "http://www.qidian.com/",
        "title": "起点中文",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.qidian.com/"
    }, {
        "url": "https://b.faloo.com/",
        "title": "飞卢小说",
        "icon": "http://www.google.cn/s2/favicons?domain=https://b.faloo.com/"
    }, {
        "url": "http://www.xxsy.net/",
        "title": "潇湘书院",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.xxsy.net/"
    }, {
        "url": "http://www.readnovel.com/",
        "title": "小说阅读",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.readnovel.com/"
    }, {
        "url": "http://www.jjwxc.net/",
        "title": "晋江文学城",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.jjwxc.net/"
    }, {
        "url": "http://www.lrts.me/",
        "title": "懒人听书",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.lrts.me/"
    }, {
        "url": "http://www.zongheng.com/",
        "title": "纵横中文网",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.zongheng.com/"
    }, {
        "url": "https://www.hongxiu.com/",
        "title": "红袖添香",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.hongxiu.com/"
    }]
}, {
    "title": "手机",
    "files": 1,
    "x": 350,
    "y": 546,
    "show": 0,
    "children": [{
        "url": "http://www.zol.com.cn/",
        "title": "中关村在线",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.zol.com.cn/"
    }, {
        "url": "http://mobile.pconline.com.cn/",
        "title": "太平洋手机",
        "icon": "http://www.google.cn/s2/favicons?domain=http://mobile.pconline.com.cn/"
    }, {
        "url": "http://www.ithome.com/",
        "title": "IT之家",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.ithome.com/"
    }, {
        "url": "http://www.10086.cn/",
        "title": "移动",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.10086.cn/"
    }, {
        "url": "http://www.skycn.com/",
        "title": "软件中心",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.skycn.com/"
    }, {
        "url": "http://www.onlinedown.net/",
        "title": "华军软件园",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.onlinedown.net/"
    }, {
        "url": "https://shouji.baidu.com/",
        "title": "百度手机助手",
        "icon": "http://www.google.cn/s2/favicons?domain=https://shouji.baidu.com/"
    }, {
        "url": "http://www.mi.com/",
        "title": "小米官网",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.mi.com/"
    }, {
        "url": "https://www.vmall.com/",
        "title": "华为官网",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.vmall.com/"
    }, {
        "url": "https://www.apple.com/cn/",
        "title": "苹果手机",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.apple.com/cn/"
    }]
}, {
    "title": "社交直播",
    "files": 1,
    "x": 350,
    "y": 546,
    "show": 0,
    "children": [{
        "url": "http://www.jiayuan.com/",
        "title": "世纪佳缘",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.jiayuan.com/"
    }, {
        "url": "http://www.zhenai.com/",
        "title": "珍爱网",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.zhenai.com/"
    }, {
        "url": "http://www.baihe.com/",
        "title": "百合网",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.baihe.com/"
    }, {
        "url": "http://www.tianya.cn/",
        "title": "天涯社区",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.tianya.cn/"
    }, {
        "url": "http://qzone.qq.com/",
        "title": "QQ空间",
        "icon": "http://www.google.cn/s2/favicons?domain=http://qzone.qq.com/"
    }, {
        "url": "http://www.mop.com/",
        "title": "猫扑",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.mop.com/"
    }, {
        "url": "https://www.douyu.com/",
        "title": "斗鱼TV",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.douyu.com/"
    }, {
        "url": "https://www.yy.com/",
        "title": "YY直播",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.yy.com/"
    }, {
        "url": "https://egame.qq.com/",
        "title": "企鹅电竞",
        "icon": "http://www.google.cn/s2/favicons?domain=https://egame.qq.com/"
    },{
        "url": "http://www.huya.com/",
        "title": "虎牙直播",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.huya.com/",
        "x": 140,
        "y": 273
    },{
        "url": "https://www.acfun.cn/",
        "title": "AcFun弹幕",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.acfun.cn/",
        "x": 210,
        "y": 273
    }, {
        "url": "http://v.6.cn/",
        "title": "六间房直播",
        "icon": "http://www.google.cn/s2/favicons?domain=http://v.6.cn/",
        "x": 140,
        "y": 273
    },
    ]
}, {
    "title": "生活",
    "files": 1,
    "x": 350,
    "y": 546,
    "show": 0,
    "children": [{
        "url": "http://jump.luna.58.com/",
        "title": "58同城",
        "icon": "http://www.google.cn/s2/favicons?domain=http://jump.luna.58.com/",
        "x": 140,
        "y": 273
    },{
        "url": "http://www.ganji.com/",
        "title": "赶集网",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.ganji.com/"
    },{
        "url": "https://www.hupu.com/",
        "title": "虎扑社区",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.hupu.com/",
        "x": 210,
        "y": 364
    }, {
        "url": "https://www.anjuke.com/",
        "title": "安居客",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.anjuke.com/"
    }, {
        "url": "http://www.fang.com/",
        "title": "房天下",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.fang.com/"
    }, {
        "url": "http://www.lianjia.com/",
        "title": "链家网",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.lianjia.com/"
    }, {
        "url": "http://www.baixing.com/",
        "title": "百姓网",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.baixing.com/"
    }, {
        "url": "http://www.xiachufang.com/",
        "title": "下厨房",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.xiachufang.com/"
    }, {
        "url": "http://www.dianping.com/",
        "title": "大众点评",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.dianping.com/"
    }, {
        "url": "https://www.tianyancha.com/",
        "title": "天眼查",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.tianyancha.com/"
    }, {
        "url": "https://meituan.com/",
        "title": "美团网",
        "icon": "http://www.google.cn/s2/favicons?domain=https://meituan.com/"
    }, {
        "url": "https://www.damai.cn/",
        "title": "大麦网",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.damai.cn/"
    },]
}, {
    "title": "旅游",
    "files": 1,
    "x": 350,
    "y": 546,
    "show": 0,
    "children": [{
        "url": "https://www.ctrip.com/",
        "title": "携程网",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.ctrip.com/"
    }, {
        "url": "http://www.elong.com/",
        "title": "艺龙旅行网",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.elong.com/"
    }, {
        "url": "https://s.click.taobao.com/8EHlH1w",
        "title": "飞猪旅行",
        "icon": "http://www.google.cn/s2/favicons?domain=https://s.click.taobao.com/8EHlH1w"
    }, {
        "url": "https://www.12306.cn/",
        "title": "12306",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.12306.cn/"
    }, {
        "url": "http://www.mafengwo.cn/",
        "title": "马蜂窝",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.mafengwo.cn/"
    }, {
        "url": "http://www.tuniu.com/",
        "title": "途牛",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.tuniu.com/"
    }, {
        "url": "http://www.qyer.com/",
        "title": "穷游网",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.qyer.com/"
    }, {
        "url": "http://www.lvmama.com/",
        "title": "驴妈妈",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.lvmama.com/"
    }, {
        "url": "https://www.ly.com/",
        "title": "同程网",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.ly.com/"
    }]
}, {
    "title": "招聘",
    "files": 1,
    "x": 350,
    "y": 546,
    "show": 0,
    "children": [{
        "url": "http://www.51job.com/",
        "title": "前程无忧",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.51job.com/"
    }, {
        "url": "https://www.liepin.com/",
        "title": "猎聘",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.liepin.com/"
    }, {
        "url": "http://www.yingjiesheng.com/",
        "title": "应届生求职",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.yingjiesheng.com/"
    }, {
        "url": "http://www.chinahr.com/",
        "title": "中华英才",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.chinahr.com/"
    }, {
        "url": "https://www.lagou.com/",
        "title": "拉勾",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.lagou.com/"
    }, {
        "url": "https://www.dajie.com/",
        "title": "大街",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.dajie.com/"
    }, {
        "url": "https://www.zhipin.com/",
        "title": "BOSS直聘",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.zhipin.com/"
    }, {
        "url": "https://www.shixiseng.com/",
        "title": "实习僧",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.shixiseng.com/"
    }, {
        "url": "https://www.kanzhun.com/",
        "title": "看准网",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.kanzhun.com/"
    }, {
        "url": "http://www.gaoxiaojob.com/",
        "title": "高校人才网",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.gaoxiaojob.com/"
    }]
}, {
    "title": "汽车",
    "files": 1,
    "x": 350,
    "y": 546,
    "show": 0,
    "children": [{
        "url": "https://jumpluna.58.com/",
        "title": "58二手车",
        "icon": "http://www.google.cn/s2/favicons?domain=https://jumpluna.58.com/"
    }, {
        "url": "https://youjia.baidu.com/",
        "title": "百度有驾",
        "icon": "http://www.google.cn/s2/favicons?domain=https://youjia.baidu.com/"
    }, {
        "url": "http://www.pcauto.com.cn/",
        "title": "太平洋汽车",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.pcauto.com.cn/"
    }, {
        "url": "http://www.bitauto.com/",
        "title": "易车网",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.bitauto.com/"
    }, {
        "url": "http://auto.sina.com.cn/",
        "title": "新浪汽车",
        "icon": "http://www.google.cn/s2/favicons?domain=http://auto.sina.com.cn/"
    }, {
        "url": "http://auto.ifeng.com/",
        "title": "凤凰汽车",
        "icon": "http://www.google.cn/s2/favicons?domain=http://auto.ifeng.com/"
    }, {
        "url": "http://www.xcar.com.cn/",
        "title": "爱卡汽车",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.xcar.com.cn/"
    }, {
        "url": "http://auto.sohu.com/",
        "title": "搜狐汽车",
        "icon": "http://www.google.cn/s2/favicons?domain=http://auto.sohu.com/"
    }, {
        "url": "http://auto.qq.com/",
        "title": "腾讯汽车",
        "icon": "http://www.google.cn/s2/favicons?domain=http://auto.qq.com/"
    }]
}, {
    "title": "音乐",
    "files": 1,
    "x": 350,
    "y": 546,
    "show": 0,
    "children": [{
        "url": "http://music.taihe.com/",
        "title": "千千音乐",
        "icon": "http://www.google.cn/s2/favicons?domain=http://music.taihe.com/"
    }, {
        "url": "http://www.kugou.com/",
        "title": "酷狗音乐",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.kugou.com/"
    }, {
        "url": "http://music.163.com/",
        "title": "网易云音乐",
        "icon": "http://www.google.cn/s2/favicons?domain=http://music.163.com/"
    }, {
        "url": "http://y.qq.com/",
        "title": "QQ音乐",
        "icon": "http://www.google.cn/s2/favicons?domain=http://y.qq.com/"
    }, {
        "url": "http://fm.taihe.com/",
        "title": "随心听",
        "icon": "http://www.google.cn/s2/favicons?domain=http://fm.taihe.com/"
    }, {
        "url": "http://www.xiami.com/",
        "title": "虾米音乐",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.xiami.com/"
    }, {
        "url": "http://music.migu.cn/v3",
        "title": "咪咕音乐",
        "icon": "http://www.google.cn/s2/favicons?domain=http://music.migu.cn/v3"
    }, {
        "url": "http://www.kuwo.cn/",
        "title": "酷我音乐",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.kuwo.cn/"
    }, {
        "url": "http://changba.com/",
        "title": "唱吧",
        "icon": "http://www.google.cn/s2/favicons?domain=http://changba.com/"
    },{
        "url": "https://www.ximalaya.com/",
        "title": "喜马拉雅FM",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.ximalaya.com/",
        "x": 140,
        "y": 182
    },]
}, {
    "title": "财经",
    "files": 1,
    "x": 350,
    "y": 546,
    "show": 0,
    "children": [{
        "url": "http://www.eastmoney.com/",
        "title": "东方财富",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.eastmoney.com/"
    }, {
        "url": "http://finance.sina.com.cn/",
        "title": "新浪财经",
        "icon": "http://www.google.cn/s2/favicons?domain=http://finance.sina.com.cn/"
    }, {
        "url": "http://www.stockstar.com/",
        "title": "证券之星",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.stockstar.com/"
    }, {
        "url": "http://www.cnfol.com/",
        "title": "中金在线",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.cnfol.com/"
    }, {
        "url": "http://finance.ifeng.com/",
        "title": "凤凰财经",
        "icon": "http://www.google.cn/s2/favicons?domain=http://finance.ifeng.com/"
    }, {
        "url": "http://www.jrj.com.cn/",
        "title": "金融界",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.jrj.com.cn/"
    }, {
        "url": "http://www.hexun.com/",
        "title": "和讯网",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.hexun.com/"
    }, {
        "url": "http://xueqiu.com/",
        "title": "雪球",
        "icon": "http://www.google.cn/s2/favicons?domain=http://xueqiu.com/"
    }, {
        "url": "http://guba.eastmoney.com/",
        "title": "股吧",
        "icon": "http://www.google.cn/s2/favicons?domain=http://guba.eastmoney.com/"
    }, {
        "url": "https://www.yicai.com/",
        "title": "第一财经",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.yicai.com/"
    }, {
        "url": "http://www.p5w.net/",
        "title": "全景网",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.p5w.net/"
    }]
}, {
    "title": "彩票",
    "files": 1,
    "x": 350,
    "y": 637,
    "show": 0,
    "children": [{
        "url": "http://www.lottery.gov.cn/",
        "title": "中国体彩",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.lottery.gov.cn/"
    }, {
        "url": "http://lottery.sina.com.cn/",
        "title": "新浪彩票",
        "icon": "http://www.google.cn/s2/favicons?domain=http://lottery.sina.com.cn/"
    }, {
        "url": "http://www.sporttery.cn/",
        "title": "竞彩网",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.sporttery.cn/"
    }, {
        "url": "http://www.cwl.gov.cn/",
        "title": "中国福彩网",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.cwl.gov.cn/"
    }, {
        "url": "http://caipiao.sohu.com/",
        "title": "搜狐彩票",
        "icon": "http://www.google.cn/s2/favicons?domain=http://caipiao.sohu.com/"
    }, {
        "url": "http://www.okooo.com/",
        "title": "澳客网",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.okooo.com/"
    }, {
        "url": "http://zx.500.com/",
        "title": "500彩票",
        "icon": "http://www.google.cn/s2/favicons?domain=http://zx.500.com/"
    }, {
        "url": "http://www.zgzcw.com/",
        "title": "中国足彩网",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.zgzcw.com/"
    }, {
        "url": "http://www.310win.com/",
        "title": "彩客网",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.310win.com/"
    }]
}, {
    "title": "银行",
    "files": 1,
    "x": 350,
    "y": 637,
    "show": 0,
    "children": [{
        "url": "http://www.icbc.com.cn/",
        "title": "工商银行",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.icbc.com.cn/"
    }, {
        "url": "http://www.ccb.com/",
        "title": "建设银行",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.ccb.com/"
    }, {
        "url": "http://www.abchina.com/",
        "title": "农业银行",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.abchina.com/"
    }, {
        "url": "http://www.boc.cn/",
        "title": "中国银行",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.boc.cn/"
    }, {
        "url": "http://www.bankcomm.com/",
        "title": "交通银行",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.bankcomm.com/"
    }, {
        "url": "http://www.cmbchina.com/",
        "title": "招商银行",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.cmbchina.com/"
    }, {
        "url": "https://www.alipay.com/",
        "title": "支付宝",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.alipay.com/"
    }, {
        "url": "http://www.pbc.gov.cn/",
        "title": "人民银行",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.pbc.gov.cn/"
    }, {
        "url": "https://www.cib.com.cn/",
        "title": "兴业银行",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.cib.com.cn/"
    }, {
        "url": "http://www.spdb.com.cn/",
        "title": "浦发银行",
        "icon": "http://www.google.cn/s2/favicons?domain=http://www.spdb.com.cn/"
    }]
}, {
    "title": "邮箱",
    "files": 1,
    "x": 350,
    "y": 637,
    "show": 0,
    "children": [{
        "url": "http://mail.163.com/",
        "title": "163邮箱",
        "icon": "http://www.google.cn/s2/favicons?domain=http://mail.163.com/"
    }, {
        "url": "http://mail.126.com/",
        "title": "126邮箱",
        "icon": "http://www.google.cn/s2/favicons?domain=http://mail.126.com/"
    }, {
        "url": "http://mail.aliyun.com/",
        "title": "阿里邮箱",
        "icon": "http://www.google.cn/s2/favicons?domain=http://mail.aliyun.com/"
    }, {
        "url": "http://mail.sina.com.cn/",
        "title": "新浪邮箱",
        "icon": "http://www.google.cn/s2/favicons?domain=http://mail.sina.com.cn/"
    }, {
        "url": "http://mail.qq.com/",
        "title": "QQ邮箱",
        "icon": "http://www.google.cn/s2/favicons?domain=http://mail.qq.com/"
    }, {
        "url": "http://mail.10086.cn/",
        "title": "139手机邮箱",
        "icon": "http://www.google.cn/s2/favicons?domain=http://mail.10086.cn/"
    }, {
        "url": "https://outlook.live.com/",
        "title": "Outlook邮箱",
        "icon": "http://www.google.cn/s2/favicons?domain=https://outlook.live.com/"
    }, {
        "url": "https://mail.sohu.com/",
        "title": "搜狐邮箱",
        "icon": "http://www.google.cn/s2/favicons?domain=https://mail.sohu.com/"
    }, {
        "url": "https://www.aliyun.com/",
        "title": "阿里云",
        "icon": "http://www.google.cn/s2/favicons?domain=https://www.aliyun.com/"
    }]
},{"url":"https://www.bilibili.com/","title":"哔哩哔哩","icon":"http://www.google.cn/s2/favicons?domain=https://www.bilibili.com/","x":560,"y":252,"id":"130"},{"url":"http://v.qq.com/","title":"腾讯视频","icon":"http://www.google.cn/s2/favicons?domain=http://v.qq.com/","id":"136","x":630,"y":252},{"url":"http://www.iqiyi.com/","title":"爱奇艺高清","icon":"http://www.google.cn/s2/favicons?domain=http://www.iqiyi.com/","id":"132","x":700,"y":252},{"url":"http://www.youku.com/","title":"优酷网","icon":"http://www.google.cn/s2/favicons?domain=http://www.youku.com/","id":"133","x":770,"y":252},{"url":"http://www.mgtv.com/","title":"芒果TV","icon":"http://www.google.cn/s2/favicons?domain=http://www.mgtv.com/","id":"137","x":490,"y":252},{"url":"https://www.ixigua.com","title":"西瓜视频","id":"1ornwu5g30f","icon":"http://www.google.cn/s2/favicons?domain=https://www.ixigua.com","x":840,"y":252}

]

export default urlList