const ICO_PREP = ''

let urlList = [{
    "title": "回收站",
    "files": 1,
    "x": 280,
    "y": 455,
    "show": 0,
    "children": []
},
// {
//     "title": "账号记录",
//     "text": 1,
//     "x": 280,
//     "y": 455,
//     "show": 0,
//     "html": '密码：123456'
// },
{
    "url": "https://account.wps.cn",
    "title": "金山文档",
    "icon": "https://account.wps.cn/favicon.ico",
    "x": 0,
    "y": 91
}, {
    "url": "http://map.baidu.com/",
    "title": "百度地图",
    "icon": "http://map.baidu.com/favicon.ico",
    "x": 0,
    "y": 91
}, {
    "url": "https://pan.baidu.com",
    "title": "百度网盘",
    "icon": "https://pan.baidu.com/static/images/favicon.ico"
}, {
    "url": "https://36kr.com/",
    "title": "36氪",
    "icon": "https://img.36krcdn.com/20191024/v2_1571894049839_img_jpg",
    "x": 70,
    "y": 182
}, {
    "url": "https://fanyi.baidu.com",
    "title": "百度翻译",
    "icon": "https://fanyi.baidu.com/favicon.ico",
    "x": 0,
    "y": 91
},
{
    "url": "https://weibo.com/",
    "title": "微博",
    "icon": "https://weibo.com/favicon.ico",
    "x": 0,
    "y": 91
}, {
    "title": "视频",
    "files": 1,
    "x": 280,
    "y": 455,
    "show": 0,
    "children": [
        {
            "url": "https://www.bilibili.com/",
            "title": "哔哩哔哩",
            "icon": "https://www.bilibili.com/favicon.ico",
            "x": 140,
            "y": 273
        }, {
            "url": "https://haokan.baidu.com/",
            "title": "好看视频",
            "icon": "https://haokan.baidu.com/favicon.ico"
        }, {
            "url": "http://www.iqiyi.com/",
            "title": "爱奇艺高清",
            "icon": "http://www.iqiyi.com/favicon.ico"
        }, {
            "url": "http://www.youku.com/",
            "title": "优酷网",
            "icon": "http://www.youku.com/favicon.ico"
        }, {
            "url": "http://v.baidu.com/",
            "title": "百度视频",
            "icon": "http://v.baidu.com/favicon.ico"
        }, {
            "url": "https://quanmin.baidu.com/",
            "title": "全民小视频",
            "icon": "https://quanmin.baidu.com/favicon.ico"
        }, {
            "url": "http://v.qq.com/",
            "title": "腾讯视频",
            "icon": "http://v.qq.com/favicon.ico"
        }, {
            "url": "http://www.mgtv.com/",
            "title": "芒果TV",
            "icon": "http://www.mgtv.com/favicon.ico"
        }, {
            "url": "https://tv.sohu.com/",
            "title": "搜狐视频",
            "icon": "https://tv.sohu.com/favicon.ico"
        }, {
            "url": "http://www.pptv.com/",
            "title": "PPTV",
            "icon": "http://www.pptv.com/favicon.ico"
        }]
}, {
    "title": "新闻",
    "files": 1,
    "x": 280,
    "y": 455,
    "show": 0,
    "children": [{
        "url": "http://news.sina.com.cn/",
        "title": "新浪新闻",
        "icon": "http://news.sina.com.cn/favicon.ico"
    }, {
        "url": "http://www.qq.com/",
        "title": "腾讯新闻",
        "icon": "http://www.qq.com/favicon.ico"
    }, {
        "url": "https://www.guancha.cn/",
        "title": "观察者网",
        "icon": "https://www.guancha.cn/favicon.ico"
    }, {
        "url": "http://news.sohu.com/",
        "title": "搜狐新闻",
        "icon": "http://news.sohu.com/favicon.ico"
    }, {
        "url": "http://www.cankaoxiaoxi.com/",
        "title": "参考消息",
        "icon": "http://www.cankaoxiaoxi.com/favicon.ico"
    }, {
        "url": "http://www.huanqiu.com/",
        "title": "环球网",
        "icon": "http://www.huanqiu.com/favicon.ico"
    }, {
        "url": "https://junshi.china.com/",
        "title": "中华军事",
        "icon": "https://junshi.china.com/favicon.ico"
    }, {
        "url": "http://news.ifeng.com/mil/",
        "title": "凤凰军事",
        "icon": "http://news.ifeng.com/mil/favicon.ico"
    }, {
        "url": "http://www.miercn.com/",
        "title": "米尔军事",
        "icon": "http://www.miercn.com/favicon.ico"
    }]
}, {
    "title": "综合",
    "files": 1,
    "x": 280,
    "y": 455,
    "show": 0,
    "children": [{
        "url": "http://www.sina.com.cn/",
        "title": "新浪",
        "icon": "http://www.sina.com.cn/favicon.ico",
        "x": 0,
        "y": 91
    }, {
        "url": "http://www.sohu.com/",
        "title": "搜狐",
        "icon": "http://www.sohu.com/favicon.ico",
        "x": 0,
        "y": 91
    }, {
        "url": "http://www.qq.com/",
        "title": "腾讯",
        "icon": "http://www.qq.com/favicon.ico",
        "x": 0,
        "y": 91
    }, {
        "url": "http://www.163.com/",
        "title": "网易",
        "icon": "http://www.163.com/favicon.ico",
        "x": 0,
        "y": 91
    }, {
        "url": "https://www.douban.com/",
        "title": "豆瓣网",
        "icon": "https://www.douban.com/favicon.ico",
        "x": 280,
        "y": 455
    }, {
        "url": "https://www.gaodun.com",
        "title": "高顿教育",
        "icon": "https://www.gaodun.com/favicon.ico"
    }, {
        "url": "https://www.58pic.com/",
        "title": "千图网",
        "icon": "https://www.58pic.com/favicon.ico"
    }, {
        "url": "https://wenku.baidu.com/",
        "title": "百度文库",
        "icon": "https://wenku.baidu.com/favicon.ico"
    }, {
        "url": "https://www.275.com/",
        "title": "学霸说保险网",
        "icon": "https://www.275.com/favicon.ico"
    }, {
        "url": "https://open.163.com",
        "title": "网易公开课",
        "icon": "https://open.163.com/favicon.ico"
    }, {
        "url": "https://www.csdn.net/",
        "title": "CSDN社区",
        "icon": "https://www.csdn.net/favicon.ico"
    }, {
        "url": "http://www.weatherol.com",
        "title": "本地天气",
        "icon": "http://www.weatherol.com/favicon.ico"
    }, {
        "url": "http://www.pbccrc.org.cn/",
        "title": "征信中心",
        "icon": "http://www.pbccrc.org.cn/favicon.ico"
    }, {
        "url": "http://www.cpta.com.cn/",
        "title": "人事考试网",
        "icon": "http://www.cpta.com.cn/favicon.ico",
        "x": 280,
        "y": 455
    }, {
        "url": "http://e.baidu.com/",
        "title": "百度营销",
        "icon": "http://e.baidu.com/favicon.ico"
    }, {
        "url": "https://www.chsi.com.cn/",
        "title": "学信网",
        "icon": "https://www.chsi.com.cn/favicon.ico",
        "x": 210,
        "y": 364
    }, {
        "url": "https://www.icourse163.org/",
        "title": "中国大学MOOC",
        "icon": "https://www.icourse163.org/favicon.ico",
        "x": 210,
        "y": 364
    }, {
        "url": "http://www.12306.cn/",
        "title": "12306",
        "icon": "http://www.12306.cn/favicon.ico",
        "x": 210,
        "y": 364
    }, {
        "url": "https://www.qcc.com/",
        "title": "企查查",
        "icon": "https://www.qcc.com/favicon.ico",
        "x": 210,
        "y": 364
    }, {
        "url": "http://www.cnki.net/",
        "title": "知网",
        "icon": "http://www.cnki.net/favicon.ico",
        "x": 140,
        "y": 273
    }, {
        "url": "http://www.zhihu.com/",
        "title": "知乎",
        "icon": "http://www.zhihu.com/favicon.ico",
        "x": 140,
        "y": 273
    }, {
        "url": "http://xueshu.baidu.com/",
        "title": "百度学术",
        "icon": "http://xueshu.baidu.com/favicon.ico",
        "x": 210,
        "y": 364
    },]
}, {
    "title": "购物",
    "files": 1,
    "x": 280,
    "y": 455,
    "show": 0,
    "children": [{
        "url": "https://s.click.taobao.com/",
        "title": "爱淘宝",
        "icon": "https://s.click.taobao.com/favicon.ico"
    }, {
        "url": "https://www.suning.com/",
        "title": "苏宁易购",
        "icon": "https://www.suning.com/favicon.ico"
    }, {
        "url": "https://mos.m.taobao.com/",
        "title": "聚划算",
        "icon": "https://mos.m.taobao.com/favicon.ico"
    }, {
        "url": "https://s.click.taobao.com",
        "title": "天猫特卖",
        "icon": "https://s.click.taobao.com/favicon.ico"
    }, {
        "url": "https://www.jd.com/",
        "title": "京东商城",
        "icon": "https://www.jd.com/favicon.ico"
    }, {
        "url": "https://s.click.taobao.com/",
        "title": "天猫超市",
        "icon": "https://s.click.taobao.com/favicon.ico"
    }, {
        "url": "https://p.yiqifa.org",
        "title": "唯品会",
        "icon": "https://p.yiqifa.org/favicon.ico",
        "x": 140,
        "y": 273
    }, {
        "url": "https://qiang.suning.com",
        "title": "苏宁秒杀",
        "icon": "https://qiang.suning.com/favicon.ico",
        "x": 140,
        "y": 273
    }, {
        "url": "http://www.dangdang.com/",
        "title": "当当网",
        "icon": "http://www.dangdang.com/favicon.ico"
    }, {
        "url": "https://www.taobao.com/",
        "title": "淘宝网",
        "icon": "https://www.taobao.com/favicon.ico"
    }, {
        "url": "http://www.mogujie.com/",
        "title": "蘑菇街",
        "icon": "http://www.mogujie.com/favicon.ico"
    }, {
        "url": "https://www.1688.com/",
        "title": "1688",
        "icon": "https://www.1688.com/favicon.ico"
    }]
}, {
    "title": "游戏",
    "files": 1,
    "x": 350,
    "y": 455,
    "show": 0,
    "children": [{
        "url": "http://www.4399.com/",
        "title": "4399游戏",
        "icon": "http://www.4399.com/4399.com/"
    }, {
        "url": "http://game.baidu.com/",
        "title": "百度游戏",
        "icon": "http://game.baidu.com/favicon.ico"
    }, {
        "url": "https://syzs.qq.com/",
        "title": "王者荣耀",
        "icon": "https://syzs.qq.com/favicon.ico"
    }, {
        "url": "http://www.7k7k.com/",
        "title": "7k7k游戏",
        "icon": "http://www.7k7k.com/favicon.ico"
    }, {
        "url": "http://www.17173.com/",
        "title": "17173",
        "icon": "http://www.17173.com/favicon.ico"
    }, {
        "url": "http://www.gamersky.com/",
        "title": "游民星空",
        "icon": "http://www.gamersky.com/favicon.ico"
    }, {
        "url": "http://game.baidu.com/",
        "title": "百度游戏",
        "icon": "http://game.baidu.com/favicon.ico"
    }]
}, {
    "title": "体育",
    "files": 1,
    "x": 350,
    "y": 455,
    "show": 0,
    "children": [{
        "url": "http://sports.sina.com.cn/",
        "title": "新浪体育",
        "icon": "http://sports.sina.com.cn/favicon.ico"
    }, {
        "url": "http://sports.sohu.com/",
        "title": "搜狐体育",
        "icon": "http://sports.sohu.com/favicon.ico"
    }, {
        "url": "http://sports.cntv.cn/",
        "title": "CCTV5",
        "icon": "http://sports.cntv.cn/favicon.ico"
    }, {
        "url": "https://www.hupu.com/",
        "title": "虎扑体育",
        "icon": "https://www.hupu.com/favicon.ico"
    }, {
        "url": "http://www.zhibo8.cc/",
        "title": "直播吧",
        "icon": "http://www.zhibo8.cc/favicon.ico"
    }, {
        "url": "http://sports.163.com/",
        "title": "网易体育",
        "icon": "http://sports.163.com/favicon.ico"
    }, {
        "url": "http://sports.qq.com/",
        "title": "腾讯体育",
        "icon": "http://sports.qq.com/favicon.ico"
    }, {
        "url": "http://sports.ifeng.com/",
        "title": "凤凰体育",
        "icon": "http://sports.ifeng.com/favicon.ico"
    }, {
        "url": "http://sports.iqiyi.com/",
        "title": "爱奇艺体育",
        "icon": "http://sports.iqiyi.com/favicon.ico"
    }]
}, {
    "title": "小说",
    "files": 1,
    "x": 350,
    "y": 546,
    "show": 0,
    "children": [{
        "url": "http://www.qidian.com/",
        "title": "起点中文",
        "icon": "http://www.qidian.com/favicon.ico"
    }, {
        "url": "https://b.faloo.com/",
        "title": "飞卢小说",
        "icon": "https://b.faloo.com/favicon.ico"
    }, {
        "url": "http://www.xxsy.net/",
        "title": "潇湘书院",
        "icon": "http://www.xxsy.net/favicon.ico"
    }, {
        "url": "http://www.readnovel.com/",
        "title": "小说阅读",
        "icon": "http://www.readnovel.com/favicon.ico"
    }, {
        "url": "http://www.jjwxc.net/",
        "title": "晋江文学城",
        "icon": "http://www.jjwxc.net/favicon.ico"
    }, {
        "url": "http://www.zongheng.com/",
        "title": "纵横中文网",
        "icon": "http://www.zongheng.com/favicon.ico"
    }, {
        "url": "https://www.hongxiu.com/",
        "title": "红袖添香",
        "icon": "https://www.hongxiu.com/favicon.ico"
    }]
}, {
    "title": "手机商城",
    "files": 1,
    "x": 350,
    "y": 546,
    "show": 0,
    "children": [{
        "url": "http://www.zol.com.cn/",
        "title": "中关村在线",
        "icon": "http://www.zol.com.cn/favicon.ico"
    }, {
        "url": "http://mobile.pconline.com.cn/",
        "title": "太平洋手机",
        "icon": "http://mobile.pconline.com.cn/favicon.ico"
    }, {
        "url": "http://www.ithome.com/",
        "title": "IT之家",
        "icon": "http://www.ithome.com/favicon.ico"
    }, {
        "url": "http://www.10086.cn/",
        "title": "移动",
        "icon": "http://www.10086.cn/favicon.ico"
    }, {
        "url": "http://www.skycn.com/",
        "title": "软件中心",
        "icon": "http://www.skycn.com/favicon.ico"
    }, {
        "url": "http://www.onlinedown.net/",
        "title": "华军软件园",
        "icon": "http://www.onlinedown.net/favicon.ico"
    }, {
        "url": "https://shouji.baidu.com/",
        "title": "百度手机助手",
        "icon": "https://shouji.baidu.com/favicon.ico"
    }, {
        "url": "http://www.mi.com/",
        "title": "小米官网",
        "icon": "http://www.mi.com/favicon.ico"
    }, {
        "url": "https://www.vmall.com/",
        "title": "华为官网",
        "icon": "https://www.vmall.com/favicon.ico"
    }, {
        "url": "https://www.apple.com/cn/",
        "title": "苹果手机",
        "icon": "https://www.apple.com/cn/favicon.ico"
    }]
}, {
    "title": "社交直播",
    "files": 1,
    "x": 350,
    "y": 546,
    "show": 0,
    "children": [{
        "url": "http://www.jiayuan.com/",
        "title": "世纪佳缘",
        "icon": "http://www.jiayuan.com/favicon.ico"
    }, {
        "url": "http://www.zhenai.com/",
        "title": "珍爱网",
        "icon": "http://www.zhenai.com/favicon.ico"
    }, {
        "url": "http://www.baihe.com/",
        "title": "百合网",
        "icon": "http://www.baihe.com/favicon.ico"
    }, {
        "url": "http://www.tianya.cn/",
        "title": "天涯社区",
        "icon": "http://www.tianya.cn/favicon.ico"
    }, {
        "url": "http://qzone.qq.com/",
        "title": "QQ空间",
        "icon": "http://qzone.qq.com/favicon.ico"
    }, {
        "url": "http://www.mop.com/",
        "title": "猫扑",
        "icon": "http://www.mop.com/favicon.ico"
    }, {
        "url": "https://www.douyu.com/",
        "title": "斗鱼TV",
        "icon": "https://www.douyu.com/favicon.ico"
    }, {
        "url": "https://www.yy.com/",
        "title": "YY直播",
        "icon": "https://www.yy.com/favicon.ico"
    }, {
        "url": "https://egame.qq.com/",
        "title": "企鹅电竞",
        "icon": "https://egame.qq.com/favicon.ico"
    }, {
        "url": "http://www.huya.com/",
        "title": "虎牙直播",
        "icon": "http://www.huya.com/favicon.ico",
        "x": 140,
        "y": 273
    }, {
        "url": "https://www.acfun.cn/",
        "title": "AcFun弹幕",
        "icon": "https://www.acfun.cn/favicon.ico",
        "x": 210,
        "y": 273
    }, {
        "url": "http://v.6.cn/",
        "title": "六间房直播",
        "icon": "http://v.6.cn/favicon.ico",
        "x": 140,
        "y": 273
    },
    ]
}, {
    "title": "生活",
    "files": 1,
    "x": 350,
    "y": 546,
    "show": 0,
    "children": [{
        "url": "http://jump.luna.58.com/",
        "title": "58同城",
        "icon": "http://jump.luna.58.com/favicon.ico",
        "x": 140,
        "y": 273
    }, {
        "url": "http://www.ganji.com/",
        "title": "赶集网",
        "icon": "http://www.ganji.com/favicon.ico"
    }, {
        "url": "https://www.hupu.com/",
        "title": "虎扑社区",
        "icon": "https://www.hupu.com/favicon.ico",
        "x": 210,
        "y": 364
    }, {
        "url": "https://www.anjuke.com/",
        "title": "安居客",
        "icon": "https://www.anjuke.com/favicon.ico"
    }, {
        "url": "http://www.fang.com/",
        "title": "房天下",
        "icon": "http://www.fang.com/favicon.ico"
    }, {
        "url": "http://www.lianjia.com/",
        "title": "链家网",
        "icon": "http://www.lianjia.com/favicon.ico"
    }, {
        "url": "http://www.baixing.com/",
        "title": "百姓网",
        "icon": "http://www.baixing.com/favicon.ico"
    }, {
        "url": "http://www.xiachufang.com/",
        "title": "下厨房",
        "icon": "http://www.xiachufang.com/favicon.ico"
    }, {
        "url": "http://www.dianping.com/",
        "title": "大众点评",
        "icon": "http://www.dianping.com/favicon.ico"
    }, {
        "url": "https://www.tianyancha.com/",
        "title": "天眼查",
        "icon": "https://www.tianyancha.com/favicon.ico"
    }, {
        "url": "https://meituan.com/",
        "title": "美团网",
        "icon": "https://meituan.com/favicon.ico"
    }, {
        "url": "https://www.damai.cn/",
        "title": "大麦网",
        "icon": "https://www.damai.cn/favicon.ico"
    },]
}, {
    "title": "旅游",
    "files": 1,
    "x": 350,
    "y": 546,
    "show": 0,
    "children": [{
        "url": "https://www.ctrip.com/",
        "title": "携程网",
        "icon": "https://www.ctrip.com/favicon.ico"
    }, {
        "url": "http://www.elong.com/",
        "title": "艺龙旅行网",
        "icon": "http://www.elong.com/favicon.ico"
    }, {
        "url": "https://s.click.taobao.com/8EHlH1w",
        "title": "飞猪旅行",
        "icon": "https://s.click.taobao.com/8EHlH1wfavicon.ico"
    }, {
        "url": "https://www.12306.cn/",
        "title": "12306",
        "icon": "https://www.12306.cn/favicon.ico"
    }, {
        "url": "http://www.mafengwo.cn/",
        "title": "马蜂窝",
        "icon": "http://www.mafengwo.cn/favicon.ico"
    }, {
        "url": "http://www.tuniu.com/",
        "title": "途牛",
        "icon": "http://www.tuniu.com/favicon.ico"
    }, {
        "url": "http://www.qyer.com/",
        "title": "穷游网",
        "icon": "http://www.qyer.com/favicon.ico"
    }, {
        "url": "http://www.lvmama.com/",
        "title": "驴妈妈",
        "icon": "http://www.lvmama.com/favicon.ico"
    }, {
        "url": "https://www.ly.com/",
        "title": "同程网",
        "icon": "https://www.ly.com/favicon.ico"
    }]
}, {
    "title": "招聘",
    "files": 1,
    "x": 350,
    "y": 546,
    "show": 0,
    "children": [{
        "url": "http://www.51job.com/",
        "title": "前程无忧",
        "icon": "http://www.51job.com/favicon.ico"
    }, {
        "url": "https://www.liepin.com/",
        "title": "猎聘",
        "icon": "https://www.liepin.com/favicon.ico"
    }, {
        "url": "http://www.yingjiesheng.com/",
        "title": "应届生求职",
        "icon": "http://www.yingjiesheng.com/favicon.ico"
    }, {
        "url": "http://www.chinahr.com/",
        "title": "中华英才",
        "icon": "http://www.chinahr.com/favicon.ico"
    }, {
        "url": "https://www.lagou.com/",
        "title": "拉勾",
        "icon": "https://www.lagou.com/favicon.ico"
    }, {
        "url": "https://www.dajie.com/",
        "title": "大街",
        "icon": "https://www.dajie.com/favicon.ico"
    }, {
        "url": "https://www.zhipin.com/",
        "title": "BOSS直聘",
        "icon": "https://www.zhipin.com/favicon.ico"
    }, {
        "url": "https://www.shixiseng.com/",
        "title": "实习僧",
        "icon": "https://www.shixiseng.com/favicon.ico"
    }, {
        "url": "https://www.kanzhun.com/",
        "title": "看准网",
        "icon": "https://www.kanzhun.com/favicon.ico"
    }, {
        "url": "http://www.gaoxiaojob.com/",
        "title": "高校人才网",
        "icon": "http://www.gaoxiaojob.com/favicon.ico"
    }]
}, {
    "title": "汽车",
    "files": 1,
    "x": 350,
    "y": 546,
    "show": 0,
    "children": [{
        "url": "https://jumpluna.58.com/",
        "title": "58二手车",
        "icon": "https://jumpluna.58.com/favicon.ico"
    }, {
        "url": "https://youjia.baidu.com/",
        "title": "百度有驾",
        "icon": "https://youjia.baidu.com/favicon.ico"
    }, {
        "url": "http://www.pcauto.com.cn/",
        "title": "太平洋汽车",
        "icon": "http://www.pcauto.com.cn/favicon.ico"
    }, {
        "url": "http://www.bitauto.com/",
        "title": "易车网",
        "icon": "http://www.bitauto.com/favicon.ico"
    }, {
        "url": "http://auto.sina.com.cn/",
        "title": "新浪汽车",
        "icon": "http://auto.sina.com.cn/favicon.ico"
    }, {
        "url": "http://auto.ifeng.com/",
        "title": "凤凰汽车",
        "icon": "http://auto.ifeng.com/favicon.ico"
    }, {
        "url": "http://www.xcar.com.cn/",
        "title": "爱卡汽车",
        "icon": "http://www.xcar.com.cn/favicon.ico"
    }, {
        "url": "http://auto.sohu.com/",
        "title": "搜狐汽车",
        "icon": "http://auto.sohu.com/favicon.ico"
    }, {
        "url": "http://auto.qq.com/",
        "title": "腾讯汽车",
        "icon": "http://auto.qq.com/favicon.ico"
    }]
}, {
    "title": "音乐",
    "files": 1,
    "x": 350,
    "y": 546,
    "show": 0,
    "children": [{
        "url": "http://music.taihe.com/",
        "title": "千千音乐",
        "icon": "http://music.taihe.com/favicon.ico"
    }, {
        "url": "http://www.kugou.com/",
        "title": "酷狗音乐",
        "icon": "http://www.kugou.com/favicon.ico"
    }, {
        "url": "http://music.163.com/",
        "title": "网易云音乐",
        "icon": "http://music.163.com/favicon.ico"
    }, {
        "url": "http://y.qq.com/",
        "title": "QQ音乐",
        "icon": "http://y.qq.com/favicon.ico"
    }, {
        "url": "http://fm.taihe.com/",
        "title": "随心听",
        "icon": "http://fm.taihe.com/favicon.ico"
    }, {
        "url": "http://www.xiami.com/",
        "title": "虾米音乐",
        "icon": "http://www.xiami.com/favicon.ico"
    }, {
        "url": "http://music.migu.cn",
        "title": "咪咕音乐",
        "icon": "http://music.migu.cn/favicon.ico"
    }, {
        "url": "http://www.kuwo.cn/",
        "title": "酷我音乐",
        "icon": "http://www.kuwo.cn/favicon.ico"
    }, {
        "url": "http://changba.com/",
        "title": "唱吧",
        "icon": "http://changba.com/favicon.ico"
    }, {
        "url": "https://www.ximalaya.com/",
        "title": "喜马拉雅FM",
        "icon": "https://www.ximalaya.com/favicon.ico",
        "x": 140,
        "y": 182
    },]
}, {
    "title": "财经",
    "files": 1,
    "x": 350,
    "y": 546,
    "show": 0,
    "children": [{
        "url": "http://www.eastmoney.com/",
        "title": "东方财富",
        "icon": "http://www.eastmoney.com/favicon.ico"
    }, {
        "url": "http://finance.sina.com.cn/",
        "title": "新浪财经",
        "icon": "http://finance.sina.com.cn/favicon.ico"
    }, {
        "url": "http://www.stockstar.com/",
        "title": "证券之星",
        "icon": "http://www.stockstar.com/favicon.ico"
    }, {
        "url": "http://finance.ifeng.com/",
        "title": "凤凰财经",
        "icon": "http://finance.ifeng.com/favicon.ico"
    }, {
        "url": "http://www.jrj.com.cn/",
        "title": "金融界",
        "icon": "http://www.jrj.com.cn/favicon.ico"
    }, {
        "url": "http://www.hexun.com/",
        "title": "和讯网",
        "icon": "http://www.hexun.com/favicon.ico"
    }, {
        "url": "http://xueqiu.com/",
        "title": "雪球",
        "icon": "http://xueqiu.com/favicon.ico"
    }, {
        "url": "http://guba.eastmoney.com/",
        "title": "股吧",
        "icon": "http://guba.eastmoney.com/favicon.ico"
    }, {
        "url": "https://www.yicai.com/",
        "title": "第一财经",
        "icon": "https://www.yicai.com/favicon.ico"
    }, {
        "url": "http://www.p5w.net/",
        "title": "全景网",
        "icon": "http://www.p5w.net/favicon.ico"
    }]
}, {
    "title": "彩票",
    "files": 1,
    "x": 350,
    "y": 637,
    "show": 0,
    "children": [{
        "url": "http://www.lottery.gov.cn/",
        "title": "中国体彩",
        "icon": "http://www.lottery.gov.cn/favicon.ico"
    }, {
        "url": "http://lottery.sina.com.cn/",
        "title": "新浪彩票",
        "icon": "http://lottery.sina.com.cn/favicon.ico"
    }, {
        "url": "http://www.sporttery.cn/",
        "title": "竞彩网",
        "icon": "http://www.sporttery.cn/favicon.ico"
    }, {
        "url": "http://www.cwl.gov.cn/",
        "title": "中国福彩网",
        "icon": "http://www.cwl.gov.cn/favicon.ico"
    }, {
        "url": "http://caipiao.sohu.com/",
        "title": "搜狐彩票",
        "icon": "http://caipiao.sohu.com/favicon.ico"
    }, {
        "url": "http://www.okooo.com/",
        "title": "澳客网",
        "icon": "http://www.okooo.com/favicon.ico"
    }, {
        "url": "http://zx.500.com/",
        "title": "500彩票",
        "icon": "http://zx.500.com/favicon.ico"
    }, {
        "url": "http://www.zgzcw.com/",
        "title": "中国足彩网",
        "icon": "http://www.zgzcw.com/favicon.ico"
    }, {
        "url": "http://www.310win.com/",
        "title": "彩客网",
        "icon": "http://www.310win.com/favicon.ico"
    }]
}, {
    "title": "银行",
    "files": 1,
    "x": 350,
    "y": 637,
    "show": 0,
    "children": [{
        "url": "http://www.icbc.com.cn/",
        "title": "工商银行",
        "icon": "http://www.icbc.com.cn/favicon.ico"
    }, {
        "url": "http://www.ccb.com/",
        "title": "建设银行",
        "icon": "http://www.ccb.com/favicon.ico"
    }, {
        "url": "http://www.abchina.com/",
        "title": "农业银行",
        "icon": "http://www.abchina.com/favicon.ico"
    }, {
        "url": "http://www.boc.cn/",
        "title": "中国银行",
        "icon": "http://www.boc.cn/favicon.ico"
    }, {
        "url": "http://www.bankcomm.com/",
        "title": "交通银行",
        "icon": "http://www.bankcomm.com/favicon.ico"
    }, {
        "url": "http://www.cmbchina.com/",
        "title": "招商银行",
        "icon": "http://www.cmbchina.com/favicon.ico"
    }, {
        "url": "https://www.alipay.com/",
        "title": "支付宝",
        "icon": "https://www.alipay.com/favicon.ico"
    }, {
        "url": "http://www.pbc.gov.cn/",
        "title": "人民银行",
        "icon": "http://www.pbc.gov.cn/favicon.ico"
    }, {
        "url": "https://www.cib.com.cn/",
        "title": "兴业银行",
        "icon": "https://www.cib.com.cn/favicon.ico"
    }, {
        "url": "http://www.spdb.com.cn/",
        "title": "浦发银行",
        "icon": "http://www.spdb.com.cn/favicon.ico"
    }]
}, 
{
    "title": "邮箱",
    "files": 1,
    "x": 350,
    "y": 637,
    "show": 0,
    "children": [{
        "url": "http://mail.163.com/",
        "title": "163邮箱",
        "icon": "http://mail.163.com/favicon.ico"
    }, {
        "url": "http://mail.126.com/",
        "title": "126邮箱",
        "icon": "http://mail.126.com/favicon.ico"
    }, {
        "url": "http://mail.aliyun.com/",
        "title": "阿里邮箱",
        "icon": "http://mail.aliyun.com/favicon.ico"
    }, {
        "url": "http://mail.sina.com.cn/",
        "title": "新浪邮箱",
        "icon": "http://mail.sina.com.cn/favicon.ico"
    }, {
        "url": "http://mail.qq.com/",
        "title": "QQ邮箱",
        "icon": "http://mail.qq.com/favicon.ico"
    }, {
        "url": "http://mail.10086.cn/",
        "title": "139手机邮箱",
        "icon": "http://mail.10086.cn/favicon.ico"
    }, {
        "url": "https://outlook.live.com/",
        "title": "Outlook邮箱",
        "icon": "https://outlook.live.com/favicon.ico"
    }, {
        "url": "https://mail.sohu.com/",
        "title": "搜狐邮箱",
        "icon": "https://mail.sohu.com/favicon.ico"
    }, {
        "url": "https://www.aliyun.com/",
        "title": "阿里云",
        "icon": "https://www.aliyun.com/favicon.ico"
    }]
},
{
    "title": "平台账号",
    "files": 1,
    "x": 350,
    "y": 637,
    "show": 0,
    "children": [{
        "url": "https://leetcode-cn.com",
        "title": "力扣",
        "icon": "https://leetcode-cn.com/favicon.ico"
    }, {
        "url": "https://juejin.im/",
        "title": "掘金",
        "icon": "https://lf3-cdn-tos.bytescm.com/obj/static/xitu_juejin_web/static/favicons/apple-touch-icon.png"
    }, {
        "url": "https://www.jianshu.com/u/45a49983cba5",
        "title": "简书",
        "icon": "https://www.jianshu.com/favicon.ico"
    }, {
        "url": "https://shimo.im/dashboard/own",
        "title": "石墨文档",
        "icon": "https://shimo.im/favicon.ico"
    }, {
        "url": "https://note.youdao.com/web/#/file/WEBca5d968ce2d571291658e1e1975be60d/note/WEB758295a2eaf70a751cb3b5bad66595ff/",
        "title": "有道云笔记",
        "icon": "https://note.youdao.com/favicon.ico"
    }, {
        "url": "https://gitee.com/",
        "title": "码云 Gitee.com",
        "icon": "https://gitee.com/favicon.ico"
    }, {
        "url": "https://www.yuque.com/dashboard",
        "title": "工作台 · 语雀",
        "icon": "https://www.yuque.com/favicon.ico"
    }, {
        "url": "https://portal.qiniu.com/kodo/bucket",
        "title": "七牛云 - 对象存储 - 空间管理",
        "icon": "https://portal.qiniu.com/favicon.ico"
    }, {
        "url": "https://www.iconfont.cn/manage/index?spm=a313x.7781069.1998910419.db775f1f3&manage_type=myprojects&projectId=1873294",
        "title": "Iconfont-阿里巴巴矢量图标库",
        "icon": "https://www.iconfont.cn/favicon.ico"
    }
]
},

{ "url": "https://www.bilibili.com/", "title": "哔哩哔哩", "icon": "https://www.bilibili.com/favicon.ico", "x": 560, "y": 252, "id": "130" },
{ "url": "http://v.qq.com/", "title": "腾讯视频", "icon": "http://v.qq.com/favicon.ico", "id": "136", "x": 630, "y": 252 },
{ "url": "http://www.iqiyi.com/", "title": "爱奇艺高清", "icon": "http://www.iqiyi.com/favicon.ico", "id": "132", "x": 700, "y": 252 },
{ "url": "http://www.youku.com/", "title": "优酷网", "icon": "http://www.youku.com/favicon.ico", "id": "133", "x": 770, "y": 252 },
{ "url": "http://www.mgtv.com/", "title": "芒果TV", "icon": "http://www.mgtv.com/favicon.ico", "id": "137", "x": 490, "y": 252 },
{ "url": "https://www.ixigua.com/", "title": "西瓜视频", "id": "1ornwsru5g30f", "icon": "https://www.ixigua.com/favicon.ico", "x": 840, "y": 252 },
{ "url": "https://mp.weixin.qq.com/", "title": "微信公众平台", "id": "1ornwudf5g30f", "icon": "https://res.wx.qq.com/a/fed_upload/9300e7ac-cec5-4454-b75c-f92260dd5b47/logo-mp.ico" },
{ "url": "https://xiumi.us/#/studio/papers", "title": "秀米", "id": "1ornwddu5g30f", "icon": "https://xiumi.us/favicon.ico" },
{ "url": "https://yiyan.baidu.com/", "title": "文心一言", "id": "ff", "icon": "https://yiyan.baidu.com/favicon.ico" },

]

export default urlList